const models = require("../../models");
const insertStudents = require("./insertStudents");

module.exports = () => {
  const data = [
    {
      subject: "Aritmética",
      topic: "Suma",
      material: [
        {
          type: "pdf",
          name: "Introducción a la suma",
          link: "/pdf/sum/Introducción sumas.pdf",
        },
        {
          type: "pdf",
          name: "Sumas (Ejemplos)",
          link: "/pdf/sum/Sumas.pdf",
        },
        {
          type: "video",
          name: "Introducción a la suma",
          link: "https://youtu.be/UFclruOiQRg",
        },
      ],
      tests: [
        {
          testName: "Sumas 1",
          qNumber: 1,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "10 + 7",
          qCorrectAnswer: "17",
        },
        {
          testName: "Sumas 1",
          qNumber: 2,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "14 + 8",
          qCorrectAnswer: "22",
        },
        {
          testName: "Sumas 1",
          qNumber: 3,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "16 + 6",
          qCorrectAnswer: "22",
        },
        {
          testName: "Sumas 1",
          qNumber: 4,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "17 + 13",
          qCorrectAnswer: "30",
        },
        {
          testName: "Sumas 1",
          qNumber: 5,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "14 + 13",
          qCorrectAnswer: "27",
        },
        {
          testName: "Sumas 1",
          qNumber: 6,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "17 + 3",
          qCorrectAnswer: "20",
        },
        {
          testName: "Sumas 1",
          qNumber: 7,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "11 + 8",
          qCorrectAnswer: "19",
        },
        {
          testName: "Sumas 1",
          qNumber: 8,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "20 + 10",
          qCorrectAnswer: "30",
        },
        {
          testName: "Sumas 1",
          qNumber: 9,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "16 + 12",
          qCorrectAnswer: "28",
        },
        {
          testName: "Sumas 1",
          qNumber: 10,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "7 + 1",
          qCorrectAnswer: "8",
        },
        {
          testName: "Sumas 1",
          qNumber: 11,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "12 + 8",
          qCorrectAnswer: "20",
        },
        {
          testName: "Sumas 1",
          qNumber: 12,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "19 + 0",
          qCorrectAnswer: "19",
        },
        {
          testName: "Sumas 1",
          qNumber: 13,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "17 + 16",
          qCorrectAnswer: "33",
        },
        {
          testName: "Sumas 1",
          qNumber: 14,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "13 + 1",
          qCorrectAnswer: "14",
        },
        {
          testName: "Sumas 1",
          qNumber: 15,
          qInstruction: "Resuelve la siguiente suma",
          qTechnicalInstruction: "16 + 12",
          qCorrectAnswer: "28",
        },
        {
          testName: "Sumas 1",
          qNumber: 16,
          qInstruction:
            "Juan tiene 10 años, mientras que Ana tiene 20 años. ¿Cuántos años suman entre los dos?",
          qCorrectAnswer: "28",
          qCorrectAnswerComplement: "años",
        },
        {
          testName: "Sumas 1",
          qNumber: 17,
          qInstruction:
            "Ernesto compró un jugo de 14 pesos y unos chicles de 10 pesos. ¿Cuánto pagó en total?",
          qCorrectAnswer: "24",
          qCorrectAnswerComplement: "pesos",
        },
        {
          testName: "Sumas 1",
          qNumber: 18,
          qInstruction:
            "En una granja hay 20 cerdos y 15 vacas. ¿Cuántos animales hay en total en la granja?",
          qCorrectAnswer: "35",
          qCorrectAnswerComplement: "animales",
        },
        {
          testName: "Sumas 1",
          qNumber: 19,
          qInstruction:
            "Una urna tiene 12 pelotas amarillas y 20 pelotas rojas. ¿Cuántas pelotas hay en total dentro de la urna?",
          qCorrectAnswer: "22",
          qCorrectAnswerComplement: "pelotas",
        },
        {
          testName: "Sumas 1",
          qNumber: 20,
          qInstruction:
            "Enrique comió 7 platanos ayer y 5 platanos hoy. ¿Cuántos plátanos se ha comido?",
          qCorrectAnswer: "12",
          qCorrectAnswerComplement: "plátanos",
        },
        {
          testName: "Sumas 2",
          qNumber: 1,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "75 + 68",
          qCorrectAnswer: "143",
        },
        {
          testName: "Sumas 2",
          qNumber: 2,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "23 + 20",
          qCorrectAnswer: "43",
        },
        {
          testName: "Sumas 2",
          qNumber: 3,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "39 + 10",
          qCorrectAnswer: "49",
        },
        {
          testName: "Sumas 2",
          qNumber: 4,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "69 + 65",
          qCorrectAnswer: "134",
        },
        {
          testName: "Sumas 2",
          qNumber: 5,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "72 + 66",
          qCorrectAnswer: "138",
        },
        {
          testName: "Sumas 2",
          qNumber: 6,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "81 + 30",
          qCorrectAnswer: "111",
        },
        {
          testName: "Sumas 2",
          qNumber: 7,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "81 + 67",
          qCorrectAnswer: "148",
        },
        {
          testName: "Sumas 2",
          qNumber: 8,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "46 + 39",
          qCorrectAnswer: "85",
        },
        {
          testName: "Sumas 2",
          qNumber: 9,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "28 + 27",
          qCorrectAnswer: "55",
        },
        {
          testName: "Sumas 2",
          qNumber: 10,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "67 + 1",
          qCorrectAnswer: "68",
        },
        {
          testName: "Sumas 2",
          qNumber: 11,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "45 + 16",
          qCorrectAnswer: "61",
        },
        {
          testName: "Sumas 2",
          qNumber: 12,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "49 + 24",
          qCorrectAnswer: "73",
        },
        {
          testName: "Sumas 2",
          qNumber: 13,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "97 + 76",
          qCorrectAnswer: "173",
        },
        {
          testName: "Sumas 2",
          qNumber: 14,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "70 + 24",
          qCorrectAnswer: "94",
        },
        {
          testName: "Sumas 2",
          qNumber: 15,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "98 + 95",
          qCorrectAnswer: "193",
        },
        {
          testName: "Sumas 2",
          qNumber: 16,
          qInstruction:
            "Alejandra compró un folder de 59 pesos y un juego de plumas de 70 pesos. ¿Cuánto pagó en total por los dos productos?",
          qCorrectAnswer: "129",
          qCorrectAnswerComplement: "pesos",
        },
        {
          testName: "Sumas 2",
          qNumber: 17,
          qInstruction:
            "En un salón de clases hay 48 niños y 39 niñas. ¿Cuántos alumnos hay en total en el salón?",
          qCorrectAnswer: "87",
          qCorrectAnswerComplement: "alumnos",
        },
        {
          testName: "Sumas 2",
          qNumber: 18,
          qInstruction:
            "En un restaurante, la ensalada cuesta 24 pesos, el plato fuerte 57 pesos y el agua 22 pesos. ¿Cuánto se debe pagar por una comida completa?",
          qCorrectAnswer: "103",
          qCorrectAnswerComplement: "pesos",
        },
        {
          testName: "Sumas 2",
          qNumber: 19,
          qInstruction:
            "Juan tiene 39 años, mientras que Ana tiene 47 años. ¿Cuántos años suman entre los dos?",
          qCorrectAnswer: "86",
          qCorrectAnswerComplement: "años",
        },
        {
          testName: "Sumas 2",
          qNumber: 20,
          qInstruction:
            "En una urna hay 50 pelotas azules y 36 pelotas rojas. ¿Cuántas pelotas hay en total dentro de la urna?",
          qCorrectAnswer: "86",
          qCorrectAnswerComplement: "pelotas",
        },
        {
          testName: "Sumas 3",
          qNumber: 1,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "939 + 57",
          qCorrectAnswer: "996",
        },
        {
          testName: "Sumas 3",
          qNumber: 2,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "925 + 465",
          qCorrectAnswer: "1390",
        },
        {
          testName: "Sumas 3",
          qNumber: 3,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "901 + 456",
          qCorrectAnswer: "1357",
        },
        {
          testName: "Sumas 3",
          qNumber: 4,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "867 + 261",
          qCorrectAnswer: "1128",
        },
        {
          testName: "Sumas 3",
          qNumber: 5,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "927 + 750",
          qCorrectAnswer: "1677",
        },
        {
          testName: "Sumas 3",
          qNumber: 6,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "331 + 0",
          qCorrectAnswer: "331",
        },
        {
          testName: "Sumas 3",
          qNumber: 7,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "114 + 106",
          qCorrectAnswer: "220",
        },
        {
          testName: "Sumas 3",
          qNumber: 8,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "996 + 694",
          qCorrectAnswer: "1690",
        },
        {
          testName: "Sumas 3",
          qNumber: 9,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "652 + 450",
          qCorrectAnswer: "1102",
        },
        {
          testName: "Sumas 3",
          qNumber: 10,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "935 + 707",
          qCorrectAnswer: "1642",
        },
        {
          testName: "Sumas 3",
          qNumber: 11,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "569 + 555",
          qCorrectAnswer: "1124",
        },
        {
          testName: "Sumas 3",
          qNumber: 12,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "983 + 932",
          qCorrectAnswer: "1915",
        },
        {
          testName: "Sumas 3",
          qNumber: 13,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "683 + 392",
          qCorrectAnswer: "1075",
        },
        {
          testName: "Sumas 3",
          qNumber: 14,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "974 + 816",
          qCorrectAnswer: "1790",
        },
        {
          testName: "Sumas 3",
          qNumber: 15,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "415 + 411",
          qCorrectAnswer: "826",
        },
        {
          testName: "Sumas 3",
          qNumber: 16,
          qInstruction:
            "En una escuela hay 834 alumnos de primaria, 772 alumnos de secundaria y 909 alumnos de preparatoria. ¿Cuántos alumnos hay en total en la escuela?",
          qCorrectAnswer: "2515",
          qCorrectAnswerComplement: "alumnos",
        },
        {
          testName: "Sumas 3",
          qNumber: 17,
          qInstruction:
            "En una granja hay 386 vacas, 585 cerdos y 450 caballos. ¿Cuántos animales hay en total en la granja?",
          qCorrectAnswer: "1421",
          qCorrectAnswerComplement: "animales",
        },
        {
          testName: "Sumas 3",
          qNumber: 18,
          qInstruction:
            "El costo de un pantalón es de 699 pesos y el de una camisa es de 646 pesos. ¿Cuánto se debe pagar por las dos prendas?",
          qCorrectAnswer: "1345",
          qCorrectAnswerComplement: "pesos",
        },
        {
          testName: "Sumas 3",
          qNumber: 19,
          qInstruction:
            "En su recorrido, un coche recorre 372 kilómetros en el primer día, mientras que en el segundo recorre 418 kilómetros. ¿Cuántos kilómetros lleva el coche recorridos al finalizar el segundo día?",
          qCorrectAnswer: "790",
          qCorrectAnswerComplement: "kilómetros",
        },
        {
          testName: "Sumas 3",
          qNumber: 20,
          qInstruction:
            "Usando los datos de su celular, Diego se gasto el viernes 319 megas y el sábado 373 megas. ¿Cuántos megas se gastó en esos dos días?",
          qCorrectAnswer: "692",
          qCorrectAnswerComplement: "megas",
        },
        {
          testName: "Sumas 4",
          qNumber: 1,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "4657 + 3016",
          qCorrectAnswer: "7663",
        },
        {
          testName: "Sumas 4",
          qNumber: 2,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3665 + 2788",
          qCorrectAnswer: "6453",
        },
        {
          testName: "Sumas 4",
          qNumber: 3,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "4956 + 1493",
          qCorrectAnswer: "6449",
        },
        {
          testName: "Sumas 4",
          qNumber: 4,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "2672 + 1404",
          qCorrectAnswer: "4076",
        },
        {
          testName: "Sumas 4",
          qNumber: 5,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "2499 + 1468",
          qCorrectAnswer: "3967",
        },
        {
          testName: "Sumas 4",
          qNumber: 6,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "4248 + 1648",
          qCorrectAnswer: "5896",
        },
        {
          testName: "Sumas 4",
          qNumber: 7,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "2890 + 1001",
          qCorrectAnswer: "3891",
        },
        {
          testName: "Sumas 4",
          qNumber: 8,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3559 + 2932",
          qCorrectAnswer: "6491",
        },
        {
          testName: "Sumas 4",
          qNumber: 9,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "4183 + 3827",
          qCorrectAnswer: "8010",
        },
        {
          testName: "Sumas 4",
          qNumber: 10,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "2957 + 2231",
          qCorrectAnswer: "5188",
        },
        {
          testName: "Sumas 4",
          qNumber: 11,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3590 + 2835",
          qCorrectAnswer: "6425",
        },
        {
          testName: "Sumas 4",
          qNumber: 12,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3643 + 2752",
          qCorrectAnswer: "6395",
        },
        {
          testName: "Sumas 4",
          qNumber: 13,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "1440 + 1213",
          qCorrectAnswer: "2653",
        },
        {
          testName: "Sumas 4",
          qNumber: 14,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3953 + 3690",
          qCorrectAnswer: "7643",
        },
        {
          testName: "Sumas 4",
          qNumber: 15,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "2560 + 1155",
          qCorrectAnswer: "3715",
        },
        {
          testName: "Sumas 4",
          qNumber: 16,
          qInstruction:
            "El salario quincenal de una persona es el siguiente: en la primera quincena gana 7040 pesos y en la segunda 7188 pesos. ¿Cuánto gana en total la persona?",
          qCorrectAnswer: "14228",
          qCorrectAnswerComplement: "pesos",
        },
        {
          testName: "Sumas 4",
          qNumber: 17,
          qInstruction:
            "Para hacer un pastel se requiere de 1584 gramos de harina y 1543 gramos de azúcar. ¿Cuál es el peso total de estos dos ingredientes?",
          qCorrectAnswer: "3127",
          qCorrectAnswerComplement: "gramos",
        },
        {
          testName: "Sumas 4",
          qNumber: 18,
          qInstruction:
            "¿Cuánto se tiene que pagar por un videojuego de 1244 pesos y un control de 1112 pesos?",
          qCorrectAnswer: "2356",
          qCorrectAnswerComplement: "pesos",
        },
        {
          testName: "Sumas 4",
          qNumber: 19,
          qInstruction:
            "Una persona quiere saber que tanto ha corrido en los últimos tres días. El primer día corrió 3352 metros, el segundo día 5281 metros y el tercer día 4862 metros. ¿Cuántos metros ha recorrido en total la persona?",
          qCorrectAnswer: "13495",
          qCorrectAnswerComplement: "metros",
        },
        {
          testName: "Sumas 4",
          qNumber: 20,
          qInstruction:
            "Una jarra tiene una capacidad para 2822 mililitros, mientras que un vaso tiene una capacidad para 1751 mililitros. ¿Cuál es la capacidad total de ambos recipientes?",
          qCorrectAnswer: "4573",
          qCorrectAnswerComplement: "mililitros",
        },
        {
          testName: "Sumas 5",
          qNumber: 1,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3065 + 1818 + 1778",
          qCorrectAnswer: "6661",
        },
        {
          testName: "Sumas 5",
          qNumber: 2,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3102 + 2813 + 2716",
          qCorrectAnswer: "8631",
        },
        {
          testName: "Sumas 5",
          qNumber: 3,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3881 + 3056 + 779",
          qCorrectAnswer: "7716",
        },
        {
          testName: "Sumas 5",
          qNumber: 4,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "1254 + 1152 + 884",
          qCorrectAnswer: "3290",
        },
        {
          testName: "Sumas 5",
          qNumber: 5,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3714 + 938 + 820",
          qCorrectAnswer: "5472",
        },
        {
          testName: "Sumas 5",
          qNumber: 6,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "2884 + 2378 + 946",
          qCorrectAnswer: "6208",
        },
        {
          testName: "Sumas 5",
          qNumber: 7,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "2703 + 1381 + 980",
          qCorrectAnswer: "5064",
        },
        {
          testName: "Sumas 5",
          qNumber: 8,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3509 + 2816 + 2722",
          qCorrectAnswer: "9047",
        },
        {
          testName: "Sumas 5",
          qNumber: 9,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "2625 + 748 + 531",
          qCorrectAnswer: "3904",
        },
        {
          testName: "Sumas 5",
          qNumber: 10,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3833 + 3066 + 601",
          qCorrectAnswer: "7500",
        },
        {
          testName: "Sumas 5",
          qNumber: 11,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "2705 + 2494 + 1040",
          qCorrectAnswer: "6239",
        },
        {
          testName: "Sumas 5",
          qNumber: 12,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3838 + 3670 + 2168",
          qCorrectAnswer: "9676",
        },
        {
          testName: "Sumas 5",
          qNumber: 13,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "2791 + 2107 + 621",
          qCorrectAnswer: "5519",
        },
        {
          testName: "Sumas 5",
          qNumber: 14,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3878 + 3025 + 2322",
          qCorrectAnswer: "9225",
        },
        {
          testName: "Sumas 5",
          qNumber: 15,
          qInstruction: "Resolver la siguiente suma",
          qTechnicalInstruction: "3789 + 3666 + 2513",
          qCorrectAnswer: "9968",
        },
        {
          testName: "Sumas 6",
          qNumber: 1,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "30 + __ = 43",
          qCorrectAnswer: "13",
        },
        {
          testName: "Sumas 6",
          qNumber: 3,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "37 + __ = 40",
          qCorrectAnswer: "3",
        },
        {
          testName: "Sumas 6",
          qNumber: 4,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "43 + __ = 46",
          qCorrectAnswer: "3",
        },
        {
          testName: "Sumas 6",
          qNumber: 5,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "42 + __ = 45",
          qCorrectAnswer: "3",
        },
        {
          testName: "Sumas 6",
          qNumber: 6,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "35 + __ = 36",
          qCorrectAnswer: "1",
        },
        {
          testName: "Sumas 6",
          qNumber: 7,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "15 + __ = 26",
          qCorrectAnswer: "11",
        },
        {
          testName: "Sumas 6",
          qNumber: 8,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "36 + __ = 38",
          qCorrectAnswer: "2",
        },
        {
          testName: "Sumas 6",
          qNumber: 9,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "45 + __ = 83",
          qCorrectAnswer: "38",
        },
        {
          testName: "Sumas 6",
          qNumber: 10,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "25 + __ = 41",
          qCorrectAnswer: "16",
        },
        {
          testName: "Sumas 6",
          qNumber: 11,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "23 + __ = 44",
          qCorrectAnswer: "21",
        },
        {
          testName: "Sumas 6",
          qNumber: 12,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "20 + __ = 28",
          qCorrectAnswer: "8",
        },
        {
          testName: "Sumas 6",
          qNumber: 13,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "37 + __ = 47",
          qCorrectAnswer: "10",
        },
        {
          testName: "Sumas 6",
          qNumber: 14,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "11 + __ = 16",
          qCorrectAnswer: "5",
        },
        {
          testName: "Sumas 6",
          qNumber: 15,
          qInstruction: "¿Cuál es el número que falta?",
          qTechnicalInstruction: "45 + __ = 61",
          qCorrectAnswer: "16",
        },
      ],
    },
  ];

  return models.PRIM_3y4.remove({})
    .then(() => {
      return models.PRIM_3y4.insertMany(data);
    })
    .then((data) => {
      console.log("===================================================");
      console.log("> " + data.length + " questions added for PRIM_3y4");
      // go to the next test
      insertStudents();
    })
    .catch((err) => {
      console.log(err);
      process.exit(1);
    });
};
